// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Demo.Portal.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ApiResult
    {
        /// <summary>
        /// Initializes a new instance of the ApiResult class.
        /// </summary>
        public ApiResult() { }

        /// <summary>
        /// Initializes a new instance of the ApiResult class.
        /// </summary>
        public ApiResult(bool? success = default(bool?), int? errorCode = default(int?), string message = default(string))
        {
            Success = success;
            ErrorCode = errorCode;
            Message = message;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "success")]
        public bool? Success { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "errorCode")]
        public int? ErrorCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

    }
}
