// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Demo.Portal.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class LoginRequest
    {
        /// <summary>
        /// Initializes a new instance of the LoginRequest class.
        /// </summary>
        public LoginRequest() { }

        /// <summary>
        /// Initializes a new instance of the LoginRequest class.
        /// </summary>
        public LoginRequest(string userName = default(string), string password = default(string))
        {
            UserName = userName;
            Password = password;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

    }
}
