// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Demo.Portal.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// 注册用户
    /// </summary>
    public partial class RegisterUserRequest
    {
        /// <summary>
        /// Initializes a new instance of the RegisterUserRequest class.
        /// </summary>
        public RegisterUserRequest() { }

        /// <summary>
        /// Initializes a new instance of the RegisterUserRequest class.
        /// </summary>
        public RegisterUserRequest(string userName, string password)
        {
            UserName = userName;
            Password = password;
        }

        /// <summary>
        /// 用户名
        /// </summary>
        [JsonProperty(PropertyName = "userName")]
        public string UserName { get; set; }

        /// <summary>
        /// 密码
        /// </summary>
        [JsonProperty(PropertyName = "password")]
        public string Password { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (UserName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "UserName");
            }
            if (Password == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Password");
            }
            if (this.UserName != null)
            {
                if (!System.Text.RegularExpressions.Regex.IsMatch(this.UserName, "^[A-Za-z0-9]+$"))
                {
                    throw new ValidationException(ValidationRules.Pattern, "UserName", "^[A-Za-z0-9]+$");
                }
            }
        }
    }
}
